### ISSUE TITLE
Optimize gallery

### ISSUE THREAD

**Issue by BlockLune** [yy4382/s3-image-port#26]
TODOs:

- [ ] #28
- [ ] Display images in a dir tree (add folder card)
- [x] #31

**Comment by yy4382** [comment]
Dir tree may be not a good view for listing photos.

> * [ ]  Display images in a dir tree (add folder card)

Filtering or sorting by key prefix, time, etc. may be implemented.

**Comment by yy4382** [comment]
Close this because the only remaining issue has its own issue.
