### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by VectorZhao** [yy4382/s3-image-port#51]
An excellent project with a very beautiful UI. Could you add support for Docker?

**Comment by yy4382** [comment]
There is a docker version now. However, it works the same as the public instance. Features like use env on server as s3 settings will be added in the future.

See instructions  on docker hub: https://hub.docker.com/repository/docker/yunfinibol/s3-image-port/general

**Comment by yy4382** [comment]
Closing this because docker is now supported (on amd64 / arm64 / armv7). 

If you want to be notified when settings sync is ready, please subscribe to #56 , which is a dedicated issue on that feature.
