### ISSUE TITLE
(style) When setting a longer Public URL, the link overflows the box during upload.

### ISSUE THREAD

**Issue by PKUcoldkeyboard** [yy4382/s3-image-port#69]
![image](https://github.com/yy4382/s3-image-port/assets/52732574/b6aee5ad-827a-42ae-ad36-3a33eebdd03b)

**Comment by yy4382** [comment]
fixed in https://github.com/yy4382/s3-image-port/commit/ebb655b01f700f18a5b7bc31817e43e036130d91
